"""Spike. Generate one ensemble config per trio sample.

Same modelling parameters as the three cell lines, taken from
`validation.core.config.CANONICAL` so the two arms cannot drift. Only the data section differs.

Two keys depart from `cell_data_section`. The trio samples have no CCDS breakpoints file, so
segments come from TAD boundaries thinned to 2 Mb. Blocks come from arc gaps, as in the cell
line arm. The segments file is written by trio_segments.py.

    python playground/trio/trio_segments.py --samples HG00512
    python playground/trio/trio_configs.py --samples HG00512
"""

import argparse
import configparser
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import trio_samples  # noqa: E402

from validation.core.config import CANONICAL, cell_data_section  # noqa: E402

BINSIZE = 25000

HEADER = """\
# {name} ({role}, {pop}) trio ensemble. TAD blocks, CTCF anchors from the CTCF site filtered
# ChIA-PET loops, ChIA-PET derived contact singletons, distance map, dynamic subanchors,
# excluded volume. Epigenome terms off. Generated by playground/trio/trio_configs.py from
# validation.core.config.CANONICAL; edit that and regenerate rather than editing this file.
#
# The contact map here is built by juicer from this sample's own ChIA-PET pairs, so the TAD
# blocks and the singletons are not independent of the loops the model fits. That differs from
# the three cell line arm, where the Hi-C came from 4DN.

"""


def build(
    sample: trio_samples.Sample, binsize: int
) -> configparser.ConfigParser:
    cfg = configparser.ConfigParser()
    params = {k: dict(v) for k, v in CANONICAL.items()}
    name = sample.name
    params["data"] = cell_data_section(name, "data")
    params["data"]["segment_split"] = f"{name}_segments.bed"
    # Blocks come from arc gaps, as in the cell line arm. A TAD boundary is an insulation call
    # that knows nothing about the arcs, so it cuts through them and the anchors either side stop
    # constraining each other. Segments stay TAD derived because the trio samples have no CCDS
    # breakpoints file and segments are not interaction blocks.
    params["data"]["ib_split"] = ""
    params["data"]["ib_split_source"] = "arcs"
    params["data"]["singletons"] = f"{name}_hic_{binsize // 1000}kb_singletons.bedpe"
    params["data"]["singletons_inter"] = ""
    params["simulation_backend"]["multigpu_mode"] = "groups"
    params["simulation_backend"]["mc_executor_jax_bucket_shapes"] = "yes"
    params["subanchor_heatmap"]["heat_min_reduction"] = "0.001"
    for sec, kv in params.items():
        cfg[sec] = {str(k): str(v) for k, v in kv.items()}
    return cfg


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--samples")
    ap.add_argument("--out-dir", default="slurm/ensemble")
    ap.add_argument("--binsize", type=int, default=BINSIZE)
    args = ap.parse_args()
    out_dir = ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    for s in trio_samples.resolve(args.samples):
        cfg = build(s, args.binsize)
        # Distinct name so the fixed arm cannot be confused with, or overwrite, the
        # 2026-08-24 configs whose structures had zero between-block contact.
        tag = "_trio"
        path = out_dir / f"{s.name.lower()}{tag}.ini"
        with path.open("w") as fh:
            fh.write(HEADER.format(name=s.name, role=s.role, pop=s.pop))
            cfg.write(fh)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
