"""Spike. Generate one ensemble config per trio sample.

Same modelling parameters as the three cell lines, taken from
`validation.core.config.CANONICAL` so the two arms cannot drift. Only the data section differs.

Two keys depart from `cell_data_section`. The trio samples have no CCDS breakpoints file, so
segments come from TAD boundaries thinned to 2 Mb. Blocks come from arc gaps, as in the cell
line arm. The segments file is written by trio_segments.py.

    python playground/trio/trio_segments.py --samples HG00512
    python playground/trio/trio_configs.py --samples HG00512

With `--factor RNAPOL2` the config carries two cluster files, the CTCF set and the sample's
RNAPOL2 set as a second factor at full strength, on the shared anchor set trio_prepare.py
writes for it, and is named `<sample>_trio_rnapol2.ini`. Everything else is the CTCF arm's.
"""

import argparse
import configparser
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import trio_samples  # noqa: E402

from validation.core.config import CANONICAL, cell_data_section  # noqa: E402

BINSIZE = 25000

HEADER = """\
# {name} ({role}, {pop}) trio ensemble. TAD blocks, CTCF anchors from the CTCF site filtered
# ChIA-PET loops, ChIA-PET derived contact singletons, distance map, dynamic subanchors,
# excluded volume. Epigenome terms off. Generated by playground/trio/trio_configs.py from
# validation.core.config.CANONICAL; edit that and regenerate rather than editing this file.
#
# The contact map here is built by juicer from this sample's own ChIA-PET pairs, so the TAD
# blocks and the singletons are not independent of the loops the model fits. That differs from
# the three cell line arm, where the Hi-C came from 4DN.
{factor_note}
"""

FACTOR_NOTE = """\
#
# {factor} arm. The sample's {factor} ChIA-PET loops are a second cluster file with their own
# strength fit, held at the multiplier in [springs] factor_strength; its loop ends that sit on
# no CTCF anchor are anchors of no orientation. On GM12878 chr1 the pull carried the expression
# signal and the anchor set carried the Hi-C cost whatever the strength, so the loops are at
# full strength, design/rnapii-loops.md.
"""


HGSVC_NOTE = """\
#
# Contact singletons from the HGSVC Hi-C of this individual, 40 kb, chr1, drawn to the depth of
# the ChIA-PET derived map they replace by playground/trio/hgsvc_singletons.py. The ChIA-PET
# derived map holds nothing the loops do not, and this one is an independent experiment,
# design/expression-from-structure.md.
"""


def build(
    sample: trio_samples.Sample, binsize: int, factor: str = "CTCF", singletons: str = "chiapet"
) -> configparser.ConfigParser:
    cfg = configparser.ConfigParser()
    params = {k: dict(v) for k, v in CANONICAL.items()}
    name = sample.name
    params["data"] = cell_data_section(name, "data")
    params["data"]["segment_split"] = f"{name}_segments.bed"
    params["data"]["singletons"] = (
        f"{name}_hic_{binsize // 1000}kb_singletons.bedpe"
        if singletons == "chiapet"
        else f"{name}_hgsvc_40kb_chr1_singletons.bedpe"
    )
    params["data"]["singletons_inter"] = ""
    if factor != "CTCF":
        tag = factor.lower()
        params["data"]["anchors"] = f"{name}_anchors_ctcf_{tag}.bed"
        params["data"]["clusters"] = f"{name}_clusters_3+.bedpe,{name}_{tag}_clusters_3+.bedpe"
        params["data"]["factors"] = f"CTCF,{factor}"
        params["springs"]["factor_strength"] = "1,1"
    params["simulation_backend"]["multigpu_mode"] = "groups"
    params["simulation_backend"]["mc_executor_jax_bucket_shapes"] = "yes"
    params["subanchor_heatmap"]["heat_min_reduction"] = "0.001"
    for sec, kv in params.items():
        cfg[sec] = {str(k): str(v) for k, v in kv.items()}
    return cfg


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--samples")
    ap.add_argument("--out-dir", default="slurm/ensemble")
    ap.add_argument("--binsize", type=int, default=BINSIZE)
    ap.add_argument("--factor", choices=("CTCF", "RNAPOL2"), default="CTCF")
    ap.add_argument("--singletons", choices=("chiapet", "hgsvc"), default="chiapet",
                    help="the contact map: the ChIA-PET derived one, or the HGSVC Hi-C")
    args = ap.parse_args()
    out_dir = ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    for s in trio_samples.resolve(args.samples):
        cfg = build(s, args.binsize, args.factor, args.singletons)
        # Distinct name so the fixed arm cannot be confused with, or overwrite, the
        # 2026-08-24 configs whose structures had zero between-block contact.
        tag = "_trio" if args.factor == "CTCF" else f"_trio_{args.factor.lower()}"
        note = "" if args.factor == "CTCF" else FACTOR_NOTE.format(factor=args.factor)
        if args.singletons == "hgsvc":
            tag += "_hgsvc"
            note += HGSVC_NOTE
        path = out_dir / f"{s.name.lower()}{tag}.ini"
        with path.open("w") as fh:
            fh.write(HEADER.format(name=s.name, role=s.role, pop=s.pop, factor_note=note))
            cfg.write(fh)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
