"""Generate the per-cell-line ensemble configs from the canonical modelling parameters.

One .ini per cell line, differing only in the data section. Generated rather than hand-written
so the cluster runs and the validation harness cannot drift apart: change
`validation.core.config.CANONICAL` and regenerate.

    python slurm/ensemble/make_configs.py
"""

import configparser
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from validation.core.config import CANONICAL, cell_data_section  # noqa: E402

CELLS = ["GM12878", "H1ESC", "HFFC6"]
BINSIZE = 25000

HEADER = """\
# {cell} ensemble: TAD blocks, CTCF anchors, Hi-C singletons, distance map, dynamic subanchors,
# excluded volume. Epigenome terms off. Generated by slurm/ensemble/make_configs.py from
# validation.core.config.CANONICAL; edit that and regenerate rather than editing this file.
#
# jax_bucket_shapes is on. Measured on one A100 chr1 conformation it cut estimate_dist 0.80h to
# 0.17h and arcs 0.23h to 0.02h at an identical bead count, by padding each IB to the shape
# ladder so a stage is a few wide launches instead of hundreds.
#
# heat_min_reduction skips the subanchor heat-distance dry pass where the achievable reduction
# is provably small. estimate_dist was 53% of a bucketed conformation.

"""


def build(cell: str) -> configparser.ConfigParser:
    cfg = configparser.ConfigParser()
    params = {k: dict(v) for k, v in CANONICAL.items()}
    params["data"] = cell_data_section(cell, "data")
    params["data"]["ib_split"] = f"{cell}_tads.bed"
    params["data"]["ib_split_source"] = "tads"
    params["data"]["singletons"] = f"{cell}_hic_{BINSIZE // 1000}kb_singletons.bedpe"
    # Hi-C replaces the ChIA-PET singletons, so the inter-chromosomal singleton file would be a
    # leftover from a different assay. Per-chromosome runs never read it anyway.
    params["data"]["singletons_inter"] = ""
    params["simulation_backend"]["multigpu_mode"] = "groups"
    params["simulation_backend"]["mc_executor_jax_bucket_shapes"] = "yes"
    params["subanchor_heatmap"]["heat_min_reduction"] = "0.001"

    for sec, kv in params.items():
        cfg[sec] = {str(k): str(v) for k, v in kv.items()}
    return cfg


def main() -> None:
    out_dir = Path(__file__).resolve().parent
    for cell in CELLS:
        cfg = build(cell)
        path = out_dir / f"{cell.lower()}_hic_tads.ini"
        with path.open("w") as fh:
            fh.write(HEADER.format(cell=cell))
            cfg.write(fh)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
