"""Generate the per-cell-line ensemble configs from the canonical modelling parameters.

One .ini per cell line, differing only in the data section. Generated rather than hand-written
so the cluster runs and the validation harness cannot drift apart: change
`validation.core.config.CANONICAL` and regenerate.

    python slurm/ensemble/make_configs.py
"""

import argparse
import configparser
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from validation.core.config import CANONICAL, cell_data_section  # noqa: E402

CELLS = ["GM12878", "H1ESC", "HFFC6"]
BINSIZE = 25000

# Which singleton source the model is driven by. "hic" is Hi-C bin pairs alone, "chiapet" the
# original PET singletons, "combined" both with ChIA-PET scaled up to equal contact mass, see
# slurm/ensemble/combine_singletons.py.
SINGLETONS = {
    "hic": "{cell}_hic_{kb}kb_singletons.bedpe",
    "chiapet": "{cell}_singletons_lessthan3.bedpe",
    "combined": "{cell}_combined_singletons.bedpe",
}

HEADER = """\
# {cell} ensemble: TAD blocks, CTCF anchors, {singletons} singletons, distance map, dynamic
# subanchors,
# excluded volume. Epigenome terms off. Generated by slurm/ensemble/make_configs.py from
# validation.core.config.CANONICAL; edit that and regenerate rather than editing this file.
#
# jax_bucket_shapes is on. Measured on one A100 chr1 conformation it cut estimate_dist 0.80h to
# 0.17h and arcs 0.23h to 0.02h at an identical bead count, by padding each IB to the shape
# ladder so a stage is a few wide launches instead of hundreds.
#
# heat_min_reduction skips the subanchor heat-distance dry pass where the achievable reduction
# is provably small. estimate_dist was 53% of a bucketed conformation.

"""


def build(
    cell: str,
    singletons: str,
    ev_weight: float | None,
    blocks: str,
    ib_arcs: float | None,
) -> configparser.ConfigParser:
    cfg = configparser.ConfigParser()
    params = {k: dict(v) for k, v in CANONICAL.items()}
    params["data"] = cell_data_section(cell, "data")
    # Block boundaries decide which loci the smooth MC couples directly, and a pair severed by a
    # boundary is positioned only by IB placement. TAD blocks are far denser than arc gaps (726
    # against 51 on chr1) and sever a third of enhancer-promoter pairs beyond 60 kb where arc
    # gaps sever 1%. Measured on a 20 Mb region, that costs a cross-block distance penalty of
    # 3.1 against 1.0. Arc gaps are the default until IB placement can hold severed pairs
    # together; TAD blocks buy better within-block contact enrichment and compartment saddle, so
    # the choice is a tradeoff rather than a fix.
    params["data"]["ib_split_source"] = blocks
    params["data"]["ib_split"] = f"{cell}_tads.bed" if blocks == "tads" else ""
    params["data"]["singletons"] = SINGLETONS[singletons].format(cell=cell, kb=BINSIZE // 1000)
    # The inter-chromosomal singleton file is a ChIA-PET artefact and would not match a Hi-C or
    # blended source. Per-chromosome runs never read it anyway.
    params["data"]["singletons_inter"] = ""
    params["simulation_backend"]["multigpu_mode"] = "groups"
    params["simulation_backend"]["mc_executor_jax_bucket_shapes"] = "yes"
    params["subanchor_heatmap"]["heat_min_reduction"] = "0.001"
    if ib_arcs is not None:
        # Attraction only: a block pair gets a target solely where its arc support implies a
        # shorter distance than its genomic separation already does.
        params["simulation_ib"]["use_ib_arcs"] = "yes"
        params["simulation_ib"]["arcs_weight"] = str(ib_arcs)
    if ev_weight is not None:
        # Excluded volume is a tradeoff, not a nuisance: weight 0.1 was picked because it
        # cut resolution-normalised overlaps 23% in 20 of 20 GM12878 regions. Lowering it
        # lets pairs with strong attractive drivers approach while random pairs still do
        # not, which is why weight is swept here rather than the radius.
        params["excluded_volume"]["weight"] = str(ev_weight)

    for sec, kv in params.items():
        cfg[sec] = {str(k): str(v) for k, v in kv.items()}
    return cfg


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--singletons", choices=sorted(SINGLETONS), default="hic")
    ap.add_argument(
        "--blocks",
        choices=["tads", "arcs"],
        default="arcs",
        help="interaction-block boundaries: arc-coverage gaps (default), or TAD calls",
    )
    ap.add_argument(
        "--ev-weight",
        type=float,
        default=None,
        help="override [excluded_volume] weight; names the file accordingly",
    )
    ap.add_argument(
        "--ib-arcs",
        type=float,
        default=None,
        metavar="WEIGHT",
        help="attraction-only cross-block arc targets in IB placement, at this weight",
    )
    args = ap.parse_args()

    out_dir = Path(__file__).resolve().parent
    for cell in CELLS:
        cfg = build(cell, args.singletons, args.ev_weight, args.blocks, args.ib_arcs)
        tag = "" if args.ev_weight is None else f"_ev{args.ev_weight:g}".replace(".", "p")
        if args.ib_arcs is not None:
            tag += f"_ibarc{args.ib_arcs:g}".replace(".", "p")
        path = out_dir / f"{cell.lower()}_{args.singletons}_{args.blocks}{tag}.ini"
        with path.open("w") as fh:
            fh.write(HEADER.format(cell=cell, singletons=args.singletons))
            cfg.write(fh)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
