"""Spike. Generate one ensemble config per mouse brain condition.

Same modelling parameters as the cell lines and the trios, taken from
`validation.core.config.CANONICAL` so the arms cannot drift. Only the data section differs.
The loops are HiCCUPS calls on each condition's own Hi-C, the singletons are that Hi-C at
25 kb thinned to production depth, and the segments are TAD boundaries thinned to 2 Mb, as on
the trios, since there is no CCDS breakpoints file for mouse.

    python playground/mouse/mouse_configs.py
"""

from __future__ import annotations

import argparse
import configparser
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from validation.core.config import CANONICAL, cell_data_section  # noqa: E402

CONDITIONS = ("E18_WT", "P60_WT", "P60_KO")

HEADER = """\
# {name} mouse brain ensemble, mm10. HiCCUPS loops as arcs, the condition's own Hi-C as
# singletons, TAD derived segments, arc gap blocks. Generated by
# playground/mouse/mouse_configs.py from validation.core.config.CANONICAL; edit that and
# regenerate rather than editing this file.

"""


def build(name: str, data_root: str) -> configparser.ConfigParser:
    cfg = configparser.ConfigParser()
    params = {k: dict(v) for k, v in CANONICAL.items()}
    params["data"] = cell_data_section(name, data_root)
    params["data"]["segment_split"] = f"{name}_segments.bed"
    params["data"]["singletons"] = f"{name}_hic_25kb_singletons.bedpe"
    params["data"]["singletons_inter"] = ""
    params["data"]["centromeres"] = ""
    for sec, kv in params.items():
        cfg[sec] = {str(k): str(v) for k, v in kv.items()}
    return cfg


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-root", default="data")
    ap.add_argument("--out-dir", default="slurm/ensemble")
    args = ap.parse_args()
    out_dir = ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    for name in CONDITIONS:
        cfg = build(name, args.data_root)
        path = out_dir / f"{name.lower()}_mouse.ini"
        with path.open("w") as fh:
            fh.write(HEADER.format(name=name))
            cfg.write(fh)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
